### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by laolarou726** [Antelcat/Antelcat.I18N#1]
作者您好，我是在 bilibili 上面评论您的网友（老腊肉726）。关于对其他 UI 框架的支持。我认为可以通过下面的方式实现：

1. 分离当前项目的实现

- 将原生成器部分独立成为基 Nuget 包（Antelcat.I18N.SourceGenerators）
- 将平台实现放到独立的支 Nuget 包中：
   - WPF 实现：Antelcat.I18N.WPF
   - Avalonia 实现：Antelcat.I18N.AvaloniaUI
   - Uno 实现：Antelcat.I18N.Uno
   - ...
 
通过这样的改进之后，我们就可以为不同的平台创造一个接口统一的实现。

**Comment by feast107** [comment]
😄十分感谢您的建议 🎆 
现在的进度是 [Antelcat.Avalonia.I18N](https://github.com/Antelcat/Antelcat.Avalonia.I18N) 中的功能已经基本实现，且测试发布。（当然Avalonia框架依然存在一些bug
目前采取的做法是共享项目和宏控制构建，尽可能利用可重用的代码，同时保证接口是一致的。
我在考虑将 [Antelcat.Avalonia.I18N](https://github.com/Antelcat/Antelcat.Avalonia.I18N) 仓库中的代码整合到当前仓库中，减少工作流上的负担。
源生成器提取到nuget毫无疑问是不错的做法，避免了在多个平台构建时可能引发冲突的问题。
