### ISSUE TITLE
[feature request] support more file type

### ISSUE THREAD

**Issue by emako** [Antelcat/Antelcat.I18N#3]
`json`，`po`等

**Comment by feast107** [comment]
更多的文件类型确实是个很美好的愿景。但首先，`.resx` 文件能行的通是因为他参与了**编译**, `msbuild` 中存在一些生成工具，这使得它能够通过某种形式转化成代码，并且跟 `Resources` 交互成为能够提取的资源。
但是 `SourceGenerator` 无法调用 `File` 类，这也就意味着只能通过`AdditionalFiles`来访问额外的文件，比如`json`，`po`等，届时再将这些文件转换并提供到资源中将会是十分繁琐的过程。
为什么不试一试格式转换呢，`.resx`的本质还是`xml`，转换起来应该很容易😸

**Comment by emako** [comment]
那么 ` SourceGenerator` 是否可以通过类似 Application.GetResourceStream(uri).Stream 访问到json文件呢？

**Comment by feast107** [comment]
`SourceGenerator` 必须以 [`.netstandard2.0` 作为目标框架](https://learn.microsoft.com/zh-cn/dotnet/csharp/roslyn-sdk/source-generators-overview) ，因此没有 Application 相关类型， 
`.netstandard`族无法作为入口程序集
