### ISSUE TITLE
语言文件resx位于独立的dll类库无法获取资源的问题

### ISSUE THREAD

**Issue by jyh583854536** [Antelcat/Antelcat.I18N#4]
我现在有一个类库和一个wpf应用程序，所有的语言resx文件和LangKeys位于类库中，wpf应用程序引用类库，这个时候在应用程序中无法获取到语言资源

**Comment by feast107** [comment]
这可能是生成工具的问题，移动了文件或者命名空间，导致 `*.Designer.cs` 中的命名空间/路径不正确，试着重新生成一下 `*.Designer.cs` 看看

**Comment by emako** [comment]
我这边排查发现，似乎是Assembly.GetEntryAssembly()的问题，Assembly.GetEntryAssembly()找的是本体exe程序集，而语言文件resx位于独立的dll，所以改成Assembly.GetExecutingAssembly()就可以让读取的Assembly跟随ResourceKeysOfAttribute生成器的程序集。

**Comment by jyh583854536** [comment]
大佬辛苦了
